# O 'version' é obsoleto e pode ser removido
services:
  db:
    image: postgres:16-alpine
    container_name: meu_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Healthcheck verifica se o Postgres está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: minha_api_node
    restart: always
    env_file:
      - .env
    ports:
      - "3333:3333" # API
      - "5555:5555" # Prisma Studio
    # Monta o código local para hot-reload
    volumes:
      - .:/app
      - /app/node_modules # Impede que o 'node_modules' local sobrescreva o do container
    depends_on:
      db:
        condition: service_healthy # Espera o healthcheck do 'db' passar
    # Roda o 'db push' ANTES de iniciar a app
    command: sh -c "npx prisma db push && npm run start"

volumes:
  postgres_data:
    driver: local
